import React from 'react'
import ProductPage from '@/components/ProductPage'
import BackButton from '@/components/Atoms/Buttons/BackButton'
import { _get } from '@/lib/api/utils'

/*
 * 1. Should be able to download a product image
 * 2. TODO: If user didn't add a product image should be generated by stable difusion
 * 3. Should be able to add a product name, it's required field
 * 4. Should be able to add a product price, it's required field
 * 5. Should be able to add a product category, or select from the list
 * */

const NewProduct = async () => {
  const shopsRequest = await _get('/api/shops')
  const { data: shops } = await shopsRequest.json()
  console.log('shops')
  console.log(shops)
  return (
    <div className='container mx-auto min-h-[calc(100%-87px)] py-10'>
      <BackButton />
      <h1 className='w-full text-center text-3xl font-bold'>Add new product</h1>
      <div className='flex min-h-[calc(100%-87px-120px)] flex-wrap items-center px-44'>
        <ProductPage />
      </div>
    </div>
  )
}

export default NewProduct
